[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/front/"
to = "/tous-les-mots/front/"

[[redirects]]
from = "/les-mots-des-parcours/creation-numerique/resolution/"
to = "/tous-les-mots/resolution/"

[[redirects]]
from = "/boucle/"
to = "/tous-les-mots/boucle/"

[[redirects]]
from = "/les-mots-des-parcours/creation-numerique/charte-graphique/"
to = "/tous-les-mots/charte-graphique/"

[[redirects]]
from = "/pictogramme/"
to = "/tous-les-mots/pictogramme/"

[[redirects]]
from = "/les-acronymes/html/"
to = "/tous-les-mots/html/"

[[redirects]]
from = "/les-mots-des-parcours/strategie-de-communication-numerique-design-dexperiences/entreprise/"
to = "/tous-les-mots/entreprise/"

[[redirects]]
from = "/les-mots/front/"
to = "/tous-les-mots/front/"

[[redirects]]
from = "/les-mots-des-parcours/developpement-web-et-dispositifs-interactifs/reseau/"
to = "/tous-les-mots/reseau/"

[[redirects]]
from = "/les-mots-des-parcours/developpement-web-et-dispositifs-interactifs/intelligence-artificielle/"
to = "/tous-les-mots/intelligence-artificielle/"

[[redirects]]
from = "/les-mots-des-parcours/strategie-de-communication-numerique-design-dexperiences/infographie/"
to = "/tous-les-mots/infographie/"

[[redirects]]
from = "/les-mots/boucle/"
to = "/tous-les-mots/boucle/"

[[redirects]]
from = "/les-mots-des-parcours/creation-numerique/pictogramme/"
to = "/tous-les-mots/pictogramme/"

[[redirects]]
from = "/les-mots-des-parcours/creation-numerique/pixel/"
to = "/tous-les-mots/pixel/"

[[redirects]]
from = "/les-thematiques/"
to = "/les-mots-des-parcours/"

[[redirects]]
from = "/les-mots/css/"
to = "/tous-les-mots/css/"

[[redirects]]
from = "/les-mots/js/"
to = "/tous-les-mots/js/"

[[redirects]]
from = "/les-mots/balisage-semantique/"
to = "/tous-les-mots/balisage-semantique/"

[[redirects]]
from = "/html/"
to = "/tous-les-mots/html/"

[[redirects]]
from = "/les-mots-des-parcours/strategie-de-communication-numerique-design-dexperiences/innover/"
to = "/tous-les-mots/innover/"

[[redirects]]
from = "/strategie-de-communication-numerique-design-dexperiences/"
to = "/les-mots-des-parcours/strategie-de-communication-numerique-design-dexperiences/"

[[redirects]]
from = "/les-mots-des-parcours/creation-numerique/calques/"
to = "/tous-les-mots/calques/"

[[redirects]]
from = "/tronc-commun/"
to = "/les-mots-des-parcours/tronc-commun/"

[[redirects]]
from = "/les-thematiques/les-mots-du-dev/"
to = "/les-mots-des-parcours/developpement-web-et-dispositifs-interactifs/"

[[redirects]]
from = "/les-acronymes/js/"
to = "/tous-les-mots/js/"

[[redirects]]
from = "/les-mots/directive/"
to = "/tous-les-mots/directive/"

[[redirects]]
from = "/les-mots/condition/"
to = "/tous-les-mots/condition/"

[[redirects]]
from = "/les-mots-des-parcours/strategie-de-communication-numerique-design-dexperiences/personae/"
to = "/tous-les-mots/personae/"

[[redirects]]
from = "/les-thematiques/developpement-web-et-dispositifs-interactifs/"
to = "/les-mots-des-parcours/developpement-web-et-dispositifs-interactifs/"

[[redirects]]
from = "/les-mots/html/"
to = "/tous-les-mots/html/"

[[redirects]]
from = "/condition/"
to = "/tous-les-mots/condition/"

[[redirects]]
from = "/les-acronymes/css/"
to = "/tous-les-mots/css/"

[[redirects]]
from = "/creation-numerique/"
to = "/les-mots-des-parcours/creation-numerique/"

[[redirects]]
from = "/directive/"
to = "/tous-les-mots/directive/"

[[redirects]]
from = "/les-mots-des-parcours/developpement-web-et-dispositifs-interactifs/developpement/"
to = "/tous-les-mots/developpement/"

[[redirects]]
from = "/les-mots/back/"
to = "/tous-les-mots/back/"

[[redirects]]
from = "/les-mots/"
to = "/tous-les-mots/"

